theme: jekyll-theme-minimal
title: How did covid impact people's interest in different philosophical topics? 
description: This stroy will explore the changes in wikipedia searches relating to beliefs, such as philosophy and religion, to give us a better understanding of how this global crisis has impacted our society
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
